### ISSUE TITLE
ES6 integration: 'class' not recognized

### ISSUE THREAD

**Issue by JVerstry** [timboudreau/nb-nodejs#44]
I was just trying to use the new features delived with ES6 in Node 4. I tried to write a 'class', but this is not considered as valid code in Netbeans, but it should. This is not an incident, it is an enhancement request.

**Comment by timboudreau** [comment]
You'll want to file a bug on that in [NetBeans' Bugzilla](https://netbeans.org/bugzilla/) - the NodeJS plugin just uses NetBeans' javascript syntax support, nothing to be done about it in this plugin.
